/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    '[error]': typeof import('./resources/js/views/[error].vue')['default']
    '[id]': typeof import('./resources/js/views/job-listing/[id].vue')['default']
    '@Index': typeof import('./resources/js/views/about/@Index.vue')['default']
    ActivityCard: typeof import('./resources/js/views/job-listing/[id]/ActivityCard.vue')['default']
    Address: typeof import('./resources/js/views/about/components/Address.vue')['default']
    AppButton: typeof import('./resources/js/components/form/AppButton.vue')['default']
    AppCard: typeof import('./resources/js/components/AppCard.vue')['default']
    AppNotifications: typeof import('./resources/js/components/AppNotifications.vue')['default']
    AppSelectInput: typeof import('./resources/js/components/form/AppSelectInput.vue')['default']
    AppTextInput: typeof import('./resources/js/components/form/AppTextInput.vue')['default']
    Banner: typeof import('./resources/js/views/about/components/Banner.vue')['default']
    CancelProcessedPrompt: typeof import('./resources/js/views/job-listing/[id]/CancelProcessedPrompt.vue')['default']
    Carousel: typeof import('./resources/js/views/index/components/Carousel.vue')['default']
    Content: typeof import('./resources/js/views/job-listing/components/Content.vue')['default']
    ContentPreloader: typeof import('./resources/js/views/job-listing/components/ContentPreloader.vue')['default']
    Count: typeof import('./resources/js/views/index/components/Count.vue')['default']
    DataTransition: typeof import('./resources/js/components/transitions/DataTransition.vue')['default']
    DeletePrompt: typeof import('./resources/js/views/dashboard/documents/components/DeletePrompt.vue')['default']
    DepartmentComponent: typeof import('./resources/js/views/job-listing/components/DepartmentComponent.vue')['default']
    FaqForm: typeof import('./resources/js/views/faqs/FaqForm.vue')['default']
    FAQs: typeof import('./resources/js/views/index/components/FAQs.vue')['default']
    Forgot: typeof import('./resources/js/views/forgot.vue')['default']
    Index: typeof import('./resources/js/views/index/index.vue')['default']
    IndividualFile: typeof import('./resources/js/views/dashboard/documents/components/IndividualFile.vue')['default']
    IndividualUser: typeof import('./resources/js/views/dashboard/users/components/IndividualUser.vue')['default']
    JobApply: typeof import('./resources/js/views/job-listing/[id]/JobApply.vue')['default']
    JobContent: typeof import('./resources/js/views/job-listing/[id]/JobContent.vue')['default']
    JobLocation: typeof import('./resources/js/views/job-listing/components/JobLocation.vue')['default']
    JobStatus: typeof import('./resources/js/views/job-listing/components/JobStatus.vue')['default']
    Login: typeof import('./resources/js/views/login.vue')['default']
    MenuCard: typeof import('./resources/js/views/dashboard/users/components/MenuCard.vue')['default']
    NotifyMeNewListing: typeof import('./resources/js/views/job-listing/components/NotifyMeNewListing.vue')['default']
    Partnership: typeof import('./resources/js/views/index/components/Partnership.vue')['default']
    Post: typeof import('./resources/js/views/index/components/Post.vue')['default']
    PricingSection: typeof import('./resources/js/views/index/components/PricingSection.vue')['default']
    Profile: typeof import('./resources/js/views/dashboard/profile.vue')['default']
    Register: typeof import('./resources/js/views/register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./resources/js/views/job-listing/components/Search.vue')['default']
    Team: typeof import('./resources/js/views/about/components/Team.vue')['default']
    Testimonial: typeof import('./resources/js/views/index/components/Testimonial.vue')['default']
    TopCard: typeof import('./resources/js/views/dashboard/documents/components/TopCard.vue')['default']
    Type: typeof import('./resources/js/views/job-listing/components/Type.vue')['default']
  }
}
